#!/usr/bin/env python3
"""
Rebuild the Springer (sn-jnl) submission version from the elsarticle sources.

Sources of truth:
  paper/main.tex            -- content (elsarticle working copy)
  paper/supplementary.tex   -- supplementary content
  paper/nrr_bundle_2026-07-06/main_nrr.tex
                            -- Springer frontmatter (authors/affiliations) and the
                               "Spectral Basis" section ported into the ESIN version

Outputs (paper/springer/): main_esin.tex, supplementary_esin.tex

Run this after ANY edit to main.tex or supplementary.tex, then compile and rezip.
"""
import re, os
from pathlib import Path

P = Path(__file__).resolve().parent.parent / "paper"
S = P / "springer"

main = (P / "main.tex").read_text()
nrr = (P / "nrr_bundle_2026-07-06" / "main_nrr.tex").read_text()

authors = re.search(r'(\\author\*\[1\].*?)\n\n\\abstract', nrr, re.S).group(1)
sb = re.search(r'(\\section\{Spectral Basis for Supervised Alteration Mapping with Sentinel-2\}'
               r'.*?\\end\{table\})', nrr, re.S).group(1)
sb = sb.replace(
 "The methodology developed in this work rests on the distinction introduced in "
 "Section~\\ref{sec:introduction}: supervised classification of pre-mapped alteration polygons "
 "does not require resolving each mineral's diagnostic absorption; it requires features that "
 "discriminate the labeled classes.",
 "The methodology developed in this work rests on a distinction that must be made explicit "
 "before any result is interpreted: supervised classification of pre-mapped alteration polygons "
 "does not require resolving each mineral's diagnostic absorption; it requires features that "
 "discriminate the labeled classes. Sentinel-2's two broad SWIR channels cannot resolve the "
 "narrow absorptions that ASTER and hyperspectral instruments use to \\emph{identify} minerals, "
 "and for unsupervised mineral identification those sensors remain the appropriate choice. "
 "The task addressed here is different, and so is the standard the sensor must meet.")

title = re.search(r'\\title\{(.*?)\}\n', main, re.S).group(1)
abstract = re.search(r'\\begin\{abstract\}\n(.*?)\n\\end\{abstract\}', main, re.S).group(1).strip()
kw = re.search(r'\\begin\{keyword\}\n(.*?)\n\\end\{keyword\}', main, re.S).group(1)
keywords = ', '.join(k.strip() for k in kw.split('\\sep'))

body = main[main.index('\\section{Introduction}'):main.index('\\section*{Data Availability}')]
body = body.replace('\\section{Study Areas}',
    sb + '\n\n\n%% ============================================================\n\\section{Study Areas}', 1)
body = body.replace('{../figures/', '{').rstrip()

# Em-dashes: la seccion portada desde el bundle NRR conserva '---' que el
# manuscrito ya no usa (AI-tell; mediana del corpus ESIN = 0). Se convierten
# a la misma puntuacion que en main.tex: incisos pareados -> parentesis,
# simples -> coma. Los '--' (en-dash de rangos) NO se tocan.
sb_fixes = [
    ("For three of the six classes considered---advanced argillic (alunite, kaolinite, pyrophyllite), argillic--phyllic (illite, sericite, smectite), and propylitic (chlorite, epidote, calcite)---the diagnostic",
     "For three of the six classes considered (advanced argillic, with alunite, kaolinite and pyrophyllite; argillic--phyllic, with illite, sericite and smectite; and propylitic, with chlorite, epidote and calcite), the diagnostic"),
    ("For the remaining two classes---silicic (vuggy silica, quartz) and potassic (biotite, K-feldspar)---no narrow diagnostic absorption exists",
     "For the remaining two classes, silicic (vuggy silica, quartz) and potassic (biotite, K-feldspar), no narrow diagnostic absorption exists"),
]
for _o, _n in sb_fixes:
    body = body.replace(_o, _n)
assert '---' not in body, f"quedan em-dashes en el cuerpo Springer: {body.count('---')}"


decl = (S / "_declarations.tex").read_text()

PREAMBLE = r"""%% Earth Science Informatics (Springer Nature) submission
%% Symbolic Regression as Spectral Feature Engineering -- Sentinel-2 Hydrothermal Alteration
%% Authors: Parra O., Rios, Latorre
%% Template: sn-jnl.cls (official, December 2024) with sn-basic reference style
%% GENERATED by scripts/build_springer.py -- edit paper/main.tex, not this file.

\documentclass[pdflatex,sn-basic]{sn-jnl}

\usepackage{graphicx}
\usepackage{multirow}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{xcolor}
\usepackage{siunitx}

\graphicspath{{./}}
\raggedbottom

\begin{document}

"""
(S / "main_esin.tex").write_text(
    PREAMBLE + f"\\title{{{title}}}\n\n{authors}\n\n\\abstract{{{abstract}}}\n\n"
    f"\\keywords{{{keywords}}}\n\n\\maketitle\n\n\n"
    "%% ============================================================\n" + body + "\n\n" + decl)

# ---- supplementary ----
sup = (P / "supplementary.tex").read_text()
sbody = sup[sup.index('\\section*{Supplementary Figures}'):sup.index('\\bibliographystyle')].rstrip()
sbody = sbody.replace('{../figures/', '{')
shead = (S / "_supp_frontmatter.tex").read_text()
(S / "supplementary_esin.tex").write_text(
    shead + "\\setcounter{figure}{0}\n\\setcounter{table}{0}\n"
    "\\renewcommand{\\thefigure}{S\\arabic{figure}}\n\\renewcommand{\\thetable}{S\\arabic{table}}\n\n"
    + sbody + "\n\n\\bibliography{references}\n\n\\end{document}\n")

print("regenerated: springer/main_esin.tex, springer/supplementary_esin.tex")
